version: "2"

services:
  nginx:
    image: nginx:1.17.8
    container_name: "laravel-nginx"
    ports:
      - "8080:80"
    volumes:
      - ./src:/src
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build: ./php
    container_name: "laravel-php"
    volumes:
      - ./src:/src
    working_dir: /src

  mysql:
    image: mysql:8.0.19
    container_name: "laravel-mysql"
    restart: always
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 13306:3306
    volumes:
      - ./mysql:/etc/mysql/conf.d
